### ISSUE TITLE
MissingRequiredParameter error

### ISSUE THREAD

**Issue by abbood** [kei-ito/hexo-deployer-aws-s3#3]
I followed the instructions just fine, but then when i run

    hexo deploy

I get this error:

```
Upload Failed: js/js.js [application/javascript]
{ MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/event_listeners.js:109:42)
    at Request.callListeners (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/abbood/dev/blog/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/config.js:308:7)
    at /Users/abbood/dev/blog/node_modules/aws-sdk/lib/config.js:348:9
    at resolveNext (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:107:9)
    at /Users/abbood/dev/blog/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:120:11
    at /Users/abbood/dev/blog/node_modules/aws-sdk/lib/credentials.js:123:23
    at /Users/abbood/dev/blog/node_modules/aws-sdk/lib/credentials/ec2_metadata_credentials.js:78:7
    at callbacks (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/metadata_service.js:97:9)
    at /Users/abbood/dev/blog/node_modules/aws-sdk/lib/metadata_service.js:102:16
    at errCallback (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/util.js:843:9)
    at ClientRequest.<anonymous> (/Users/abbood/dev/blog/node_modules/aws-sdk/lib/http/node.js:56:7)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:626:10)
  message: 'Missing required key \'Bucket\' in params',
  code: 'MissingRequiredParameter',
  time: 2017-02-04T11:25:58.066Z }
Upload Failed: img/random/material-7.png [image/png]
```

this is what my _config.yml file looks like

```
deploy:
- type: git
  repo: https://github.com/abbood/my-blog.git
  branch: master
- type: aws-s3
  bucket: blog.lobolabshq.com
  region: Oregon
```

**Comment by kei-ito** [comment]
Thank you @abbood .
The deployer didn't support multiple deployers.
I've fixed it and published the new version, 0.1.4.
Please update the deployer.
